config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

	get 'welcome/index'

  resources :welcome do
    collection do
      get 'startBot'
      get 'stopBot'
    end
  end

  resources :authentication, only: [:index] do
    collection do
      get 'saveUserInfo'
      get 'getBotOauth'
      get 'getUserOauth'
    end
    member do
      post 'saveUserOauth'
      post 'saveBotOauth'
    end
  end

  resources :points, only: [:index] do
    collection do
      get 'fillFollowers'
      get 'savePointsConfig'
    end
  end

  resources :testbot, only: [:index]

  resources :commands, only: [:index] do
    collection do
      get 'addCommand'
      get 'editCommand'
    end
  end

	root 'welcome#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shembot</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div>
  	<p>Welcome to Shembot</p>
  	<p>A Custom Twitch Bot</p>
  </div>

  <div>
    <ul class='nav'>
      <li id='startBot' style='display:<%=$botStatus ? 'none' : 'block'%>'><a href='#' onclick='startBot()'>Connect</a></li>
      <li id='stopBot' style='display:<%=$botStatus ? 'block' : 'none'%>'><a href='#' onclick='stopBot()'>Disconnect</a></li>
      <li><%= link_to "Authentication", authentication_index_path %></li>
      <li><%= link_to "Points", points_path %></li>
      <li><%= link_to "Commands", commands_path%></li>
    </ul>
  </div>
<%= yield %>

</body>
</html>